[package]
name = "coding_quizzer_minigrep"
version = "0.1.0"
edition = "2021"
description = "Mini grep from rust book"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
